version: '3'

services:
  mongo_db:
    image: mongo:latest
    container_name: database_container
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    container_name: app
    restart: always
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo_db:27017/stage
    ports:
      - 3000:3000
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}